-- Supabase table: notes
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  title text,
  body text,
  created_at timestamp with time zone default now()
);
